name: Update Submodule

on:
  repository_dispatch:
    types: [update_submodule]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Create Notification Issue
      uses: actions/github-script@v6
      with:
        script: |
         const github = require('@actions/github');
         const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
         await octokit.issues.create({
         owner: github.context.repo.owner,
         repo: github.context.repo.repo,
         title: "Submodule Update Notification",
         body: "Submodule update has been detected.",
         labels:["Notification"]});
      env:
       GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
