name: Update Submodule

on:
  repository_dispatch:
    types: [update_submodule]

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v3
      with:
        token: ${{ github.event.client_payload }}
        submodules: recursive  
        
    - name: Configure git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@user.noreply.github.com"    
    - name: Initialize submodule
      run: |
          git submodule sync
          git submodule update --init --recursive
      
    - name: Reset submodule to latest remote state on main branch
      run: |
          cd Core
          git fetch --all 
          git reset --hard origin/main
          cd ..
            
    - name: Commit and Push Changes if any
      run: |
          git add .
          git commit -m "Submodule updated to latest commit from Remote" || echo "No commit to Change"
          git push origin HEAD:${{ github.ref }} 
