name: Update Submodule

on:
  repository_dispatch:
    types: [update_submodule]

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GIT_TOKEN }}
        submodules: true  # Checkout submodules as well

    - name: Configure git
      run: |
        git config --global user.name 'RaajGurunathan'
        git config --global user.email 'rajkumar.gurunathan90@gmail.com'

    - name: Update submodule
      run: |
        git submodule foreach --recursive
        git pull origin main 
        if ! git diff --quiet --exit-code; then
          git add .
          git commit -m 'Update submodule to latest commit'
          git push origin HEAD:${{ github.ref }} 
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
