name: Update Submodule

on:
  repository_dispatch:
    types: [update_submodule]

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GIT_TOKEN }}
        submodules: recursive  
  
    - name: Initialize submodule
      run: git submodule update --init --recursive
      
    - name: Fetch Latest Change for submodule
      run: git fetch -all 
    - name: Reset submodule to latest remote state on main branch
      run: git reset --hard origin/main
    - name: Commit and Push Changes if any
      run: |
        if ! git diff --quiet --exit-code; then
          git add .
          git commit -m 'Update submodule to latest commit'
          git push origin HEAD:${{ github.ref }} 
        fi
    env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
