name: Update Submodule

on:
  repository_dispatch:
    types: [update_submodule]

permissions:
  issues: write
  
jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Create Notification Issue
      uses: actions/github-script@v6
      with:
        script: |
          await github.rest.issues.create({
          owner: context.repo.owner,
          repo: context.repo.repo,
          title: "Submodule Update Notification",
          body: "Submodule update has been detected.",
          labels:["Notification"]});
