name: Update Submodule

on:
  repository_dispatch:
    types: [update_submodule]

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GIT_TOKEN }}
        submodules: recursive  
        
    - name: Configure git
      run: |
        git config --global user.name 'RaajGurunathan'
        git config --global user.email 'rajkumar.gurunathan90@gmail.com'
        
    - name: Initialize submodule
      run: |
          git submodule sync
          git submodule update --init --recursive --force
      
    - name: Fetch Latest Change for submodule
      run: git fetch --all 
    - name: Reset submodule to latest remote state on main branch
      run: git reset --hard origin/main
    - name: Commit and Push Changes if any
      run: |
          git add .
          git commit -m "Update submodule to latest commit" || echo "No commit to Change"
          git push origin HEAD:${{ github.ref }} 
    env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
